# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Verilog_projects/FIFO_Advanced/Codes/20241211_114116.xdc

# IP: ip/ILA_Read/ILA_Read.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA_Read || ORIG_REF_NAME==ILA_Read} -quiet] -quiet

# IP: ip/ILA_Write/ILA_Write.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA_Write || ORIG_REF_NAME==ILA_Write} -quiet] -quiet
