# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 8
create_project -in_memory -part xc7a200tsbg484-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/Project_FIFO/Project_FIFO.cache/wt [current_project]
set_property parent.project_path /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/Project_FIFO/Project_FIFO.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/Project_FIFO/Project_FIFO.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/FIFO_memory.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/bin2gray.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/clock_divider.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/debouncer.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/edge_detector.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/fifo_fsm.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/gray2bin.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/lut_rom.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/read_controller.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/read_pntr_handler.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/synchronizer.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/write_pntr_handler.v
  /home/staj2/Documents/MetehanAkilli_Verilog_Projects/FIFO_Advanced/top_module_FIFO.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_module_FIFO -part xc7a200tsbg484-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module_FIFO.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_FIFO_utilization_synth.rpt -pb top_module_FIFO_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
